file_loc: "D:/Data_science/personal_data_science_projects/crime_bangalore/data/scraped_data/bm_all_data.txt"
months: {
        'jan': 1,
        'feb': 2,
        'mar': 3,
        'apr': 4,
         'may': 5,
         'jun': 6,
         'jul': 7,
         'aug': 8,
         'sep': 9,
         'oct': 10,
         'nov': 11,
         'dec': 12
        }